import type { ToolDefinition, Binding } from "@/types";

const bindings: Binding[] = [
  {
    id: "tmux-prefix",
    tool: "tmux",
    actionId: "prefix",
    action: "Prefix key",
    sequence: [{ modifiers: ["ctrl"], key: "b" }],
    category: "core",
    difficulty: 1,
  },
  {
    id: "tmux-new-window",
    tool: "tmux",
    actionId: "window.create",
    action: "Create new window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "c" }],
    category: "window",
    difficulty: 1,
  },
  {
    id: "tmux-next-window",
    tool: "tmux",
    actionId: "window.next",
    action: "Next window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "n" }],
    category: "window",
    difficulty: 1,
  },
  {
    id: "tmux-prev-window",
    tool: "tmux",
    actionId: "window.prev",
    action: "Previous window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "p" }],
    category: "window",
    difficulty: 1,
  },
  {
    id: "tmux-select-window-0",
    tool: "tmux",
    actionId: "window.select.0",
    action: "Select window 0",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "0" }],
    category: "window",
    difficulty: 2,
  },
  {
    id: "tmux-select-window-1",
    tool: "tmux",
    actionId: "window.select.1",
    action: "Select window 1",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "1" }],
    category: "window",
    difficulty: 2,
  },
  {
    id: "tmux-rename-window",
    tool: "tmux",
    actionId: "window.rename",
    action: "Rename window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "," }],
    category: "window",
    difficulty: 2,
  },
  {
    id: "tmux-close-window",
    tool: "tmux",
    actionId: "window.close",
    action: "Close window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "7" }],
    category: "window",
    difficulty: 2,
  },
  {
    id: "tmux-split-horizontal",
    tool: "tmux",
    actionId: "pane.split.horizontal",
    action: "Split pane horizontally",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "5" }],
    category: "pane",
    difficulty: 1,
  },
  {
    id: "tmux-split-vertical",
    tool: "tmux",
    actionId: "pane.split.vertical",
    action: "Split pane vertically",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "'" }],
    category: "pane",
    difficulty: 1,
  },
  {
    id: "tmux-pane-left",
    tool: "tmux",
    actionId: "pane.focus.left",
    action: "Move to left pane",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "left" }],
    category: "pane",
    difficulty: 2,
  },
  {
    id: "tmux-pane-right",
    tool: "tmux",
    actionId: "pane.focus.right",
    action: "Move to right pane",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "right" }],
    category: "pane",
    difficulty: 2,
  },
  {
    id: "tmux-pane-up",
    tool: "tmux",
    actionId: "pane.focus.up",
    action: "Move to pane above",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "up" }],
    category: "pane",
    difficulty: 2,
  },
  {
    id: "tmux-pane-down",
    tool: "tmux",
    actionId: "pane.focus.down",
    action: "Move to pane below",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "down" }],
    category: "pane",
    difficulty: 2,
  },
  {
    id: "tmux-close-pane",
    tool: "tmux",
    actionId: "pane.close",
    action: "Close current pane",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "x" }],
    category: "pane",
    difficulty: 1,
  },
  {
    id: "tmux-zoom-pane",
    tool: "tmux",
    actionId: "pane.zoom.toggle",
    action: "Toggle pane zoom",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "z" }],
    category: "pane",
    difficulty: 2,
  },
  {
    id: "tmux-resize-pane-left",
    tool: "tmux",
    actionId: "pane.resize.left",
    action: "Resize pane left",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["ctrl"], key: "left" }],
    category: "pane",
    difficulty: 3,
  },
  {
    id: "tmux-resize-pane-right",
    tool: "tmux",
    actionId: "pane.resize.right",
    action: "Resize pane right",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["ctrl"], key: "right" }],
    category: "pane",
    difficulty: 3,
  },
  {
    id: "tmux-copy-mode",
    tool: "tmux",
    actionId: "mode.copy",
    action: "Enter copy mode",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "[" }],
    category: "copy",
    difficulty: 2,
  },
  {
    id: "tmux-paste",
    tool: "tmux",
    actionId: "buffer.paste",
    action: "Paste buffer",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "]" }],
    category: "copy",
    difficulty: 2,
  },
  {
    id: "tmux-new-session",
    tool: "tmux",
    actionId: "session.create",
    action: "New session",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: ";" }],
    category: "session",
    difficulty: 3,
  },
  {
    id: "tmux-detach",
    tool: "tmux",
    actionId: "session.detach",
    action: "Detach from session",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "d" }],
    category: "session",
    difficulty: 1,
  },
  {
    id: "tmux-list-sessions",
    tool: "tmux",
    actionId: "session.list",
    action: "List sessions",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "s" }],
    category: "session",
    difficulty: 2,
  },
  {
    id: "tmux-rename-session",
    tool: "tmux",
    actionId: "session.rename",
    action: "Rename session",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "4" }],
    category: "session",
    difficulty: 3,
  },
  {
    id: "tmux-command-mode",
    tool: "tmux",
    actionId: "mode.command",
    action: "Enter command mode",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: ";" }],
    category: "core",
    difficulty: 2,
  },
  {
    id: "tmux-list-keys",
    tool: "tmux",
    actionId: "keys.list",
    action: "List key bindings",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "/" }],
    category: "core",
    difficulty: 3,
  },
  {
    id: "tmux-swap-pane-down",
    tool: "tmux",
    actionId: "pane.swap.down",
    action: "Swap pane down",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "}" }],
    category: "pane",
    difficulty: 3,
  },
  {
    id: "tmux-swap-pane-up",
    tool: "tmux",
    actionId: "pane.swap.up",
    action: "Swap pane up",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: ["shift"], key: "{" }],
    category: "pane",
    difficulty: 3,
  },
  {
    id: "tmux-last-window",
    tool: "tmux",
    actionId: "window.last",
    action: "Last active window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "l" }],
    category: "window",
    difficulty: 2,
  },
  {
    id: "tmux-find-window",
    tool: "tmux",
    actionId: "window.find",
    action: "Find window",
    sequence: [{ modifiers: ["ctrl"], key: "b" }, { modifiers: [], key: "f" }],
    category: "window",
    difficulty: 3,
  },
];

export const tmux: ToolDefinition = {
  id: "tmux",
  name: "Tmux",
  bindings,
  difficultyCurve: {
    warmup: 8,
    mastery: 60,
  },
};