import type { ToolDefinition, Binding } from "@/types";

const bindings: Binding[] = [
  {
    id: "vim-motion-h",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.left",
    action: "Move cursor left",
    sequence: [{ modifiers: [], key: "h" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-j",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.down",
    action: "Move cursor down",
    sequence: [{ modifiers: [], key: "j" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-k",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.up",
    action: "Move cursor up",
    sequence: [{ modifiers: [], key: "k" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-l",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.right",
    action: "Move cursor right",
    sequence: [{ modifiers: [], key: "l" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-w",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.word.next",
    action: "Move to next word",
    sequence: [{ modifiers: [], key: "w" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-b",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.word.prev",
    action: "Move to previous word",
    sequence: [{ modifiers: [], key: "b" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-e",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.word.end",
    action: "Move to end of word",
    sequence: [{ modifiers: [], key: "e" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-0",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.line.start",
    action: "Move to start of line",
    sequence: [{ modifiers: [], key: "0" }],
    category: "motion",
    difficulty: 1,
  },
  {
    id: "vim-motion-dollar",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.line.end",
    action: "Move to end of line",
    sequence: [{ modifiers: [], key: "$" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-caret",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.line.firstNonBlank",
    action: "Move to first non-blank character",
    sequence: [{ modifiers: [], key: "^" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-gg",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.file.start",
    action: "Go to first line",
    sequence: [{ modifiers: [], key: "g" }, { modifiers: [], key: "g" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-G",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.file.end",
    action: "Go to last line",
    sequence: [{ modifiers: ["shift"], key: "g" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-insert-i",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert",
    action: "Enter insert mode",
    sequence: [{ modifiers: [], key: "i" }],
    category: "mode",
    difficulty: 1,
  },
  {
    id: "vim-insert-a",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert.after",
    action: "Insert after cursor",
    sequence: [{ modifiers: [], key: "a" }],
    category: "mode",
    difficulty: 1,
  },
  {
    id: "vim-insert-I",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert.lineStart",
    action: "Insert at line start",
    sequence: [{ modifiers: ["shift"], key: "i" }],
    category: "mode",
    difficulty: 2,
  },
  {
    id: "vim-insert-A",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert.lineEnd",
    action: "Insert at line end",
    sequence: [{ modifiers: ["shift"], key: "a" }],
    category: "mode",
    difficulty: 2,
  },
  {
    id: "vim-insert-o",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert.lineBelow",
    action: "Open line below",
    sequence: [{ modifiers: [], key: "o" }],
    category: "mode",
    difficulty: 1,
  },
  {
    id: "vim-insert-O",
    tool: "vim",
    mode: "normal",
    actionId: "mode.insert.lineAbove",
    action: "Open line above",
    sequence: [{ modifiers: ["shift"], key: "o" }],
    category: "mode",
    difficulty: 2,
  },
  {
    id: "vim-edit-x",
    tool: "vim",
    mode: "normal",
    actionId: "edit.delete.char",
    action: "Delete character",
    sequence: [{ modifiers: [], key: "x" }],
    category: "edit",
    difficulty: 1,
  },
  {
    id: "vim-edit-dd",
    tool: "vim",
    mode: "normal",
    actionId: "edit.delete.line",
    action: "Delete line",
    sequence: [{ modifiers: [], key: "d" }, { modifiers: [], key: "d" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-dw",
    tool: "vim",
    mode: "normal",
    actionId: "edit.delete.word",
    action: "Delete word",
    sequence: [{ modifiers: [], key: "d" }, { modifiers: [], key: "w" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-yy",
    tool: "vim",
    mode: "normal",
    actionId: "edit.yank.line",
    action: "Yank (copy) line",
    sequence: [{ modifiers: [], key: "y" }, { modifiers: [], key: "y" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-p",
    tool: "vim",
    mode: "normal",
    actionId: "edit.paste.after",
    action: "Paste after cursor",
    sequence: [{ modifiers: [], key: "p" }],
    category: "edit",
    difficulty: 1,
  },
  {
    id: "vim-edit-P",
    tool: "vim",
    mode: "normal",
    actionId: "edit.paste.before",
    action: "Paste before cursor",
    sequence: [{ modifiers: ["shift"], key: "p" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-u",
    tool: "vim",
    mode: "normal",
    actionId: "edit.undo",
    action: "Undo",
    sequence: [{ modifiers: [], key: "u" }],
    category: "edit",
    difficulty: 1,
  },
  {
    id: "vim-edit-ctrl-r",
    tool: "vim",
    mode: "normal",
    actionId: "edit.redo",
    action: "Redo",
    sequence: [{ modifiers: ["ctrl"], key: "r" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-visual-v",
    tool: "vim",
    mode: "normal",
    actionId: "mode.visual",
    action: "Enter visual mode",
    sequence: [{ modifiers: [], key: "v" }],
    category: "mode",
    difficulty: 1,
  },
  {
    id: "vim-visual-V",
    tool: "vim",
    mode: "normal",
    actionId: "mode.visual.line",
    action: "Enter visual line mode",
    sequence: [{ modifiers: ["shift"], key: "v" }],
    category: "mode",
    difficulty: 2,
  },
  {
    id: "vim-visual-ctrl-v",
    tool: "vim",
    mode: "normal",
    actionId: "mode.visual.block",
    action: "Enter visual block mode",
    sequence: [{ modifiers: ["ctrl"], key: "v" }],
    category: "mode",
    difficulty: 3,
  },
  {
    id: "vim-search-slash",
    tool: "vim",
    mode: "normal",
    actionId: "search.forward",
    action: "Search forward",
    sequence: [{ modifiers: [], key: "/" }],
    category: "search",
    difficulty: 1,
  },
  {
    id: "vim-search-question",
    tool: "vim",
    mode: "normal",
    actionId: "search.backward",
    action: "Search backward",
    sequence: [{ modifiers: ["shift"], key: "/" }],
    category: "search",
    difficulty: 2,
  },
  {
    id: "vim-search-n",
    tool: "vim",
    mode: "normal",
    actionId: "search.next",
    action: "Next search result",
    sequence: [{ modifiers: [], key: "n" }],
    category: "search",
    difficulty: 1,
  },
  {
    id: "vim-search-N",
    tool: "vim",
    mode: "normal",
    actionId: "search.prev",
    action: "Previous search result",
    sequence: [{ modifiers: ["shift"], key: "n" }],
    category: "search",
    difficulty: 2,
  },
  {
    id: "vim-motion-percent",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.move.bracket.match",
    action: "Jump to matching bracket",
    sequence: [{ modifiers: ["shift"], key: "5" }],
    category: "motion",
    difficulty: 3,
  },
  {
    id: "vim-edit-cc",
    tool: "vim",
    mode: "normal",
    actionId: "edit.change.line",
    action: "Change entire line",
    sequence: [{ modifiers: [], key: "c" }, { modifiers: [], key: "c" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-cw",
    tool: "vim",
    mode: "normal",
    actionId: "edit.change.word",
    action: "Change word",
    sequence: [{ modifiers: [], key: "c" }, { modifiers: [], key: "w" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-ciw",
    tool: "vim",
    mode: "normal",
    actionId: "edit.change.inner.word",
    action: "Change inner word",
    sequence: [{ modifiers: [], key: "c" }, { modifiers: [], key: "i" }, { modifiers: [], key: "w" }],
    category: "edit",
    difficulty: 3,
  },
  {
    id: "vim-edit-di-paren",
    tool: "vim",
    mode: "normal",
    actionId: "edit.delete.inner.paren",
    action: "Delete inside parentheses",
    sequence: [{ modifiers: [], key: "d" }, { modifiers: [], key: "i" }, { modifiers: ["shift"], key: "9" }],
    category: "edit",
    difficulty: 4,
  },
  {
    id: "vim-command-colon-w",
    tool: "vim",
    mode: "normal",
    actionId: "file.save",
    action: "Save file",
    sequence: [{ modifiers: ["shift"], key: ";" }],
    category: "command",
    difficulty: 1,
  },
  {
    id: "vim-motion-f",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.find.char.forward",
    action: "Find character forward",
    sequence: [{ modifiers: [], key: "f" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-F",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.find.char.backward",
    action: "Find character backward",
    sequence: [{ modifiers: ["shift"], key: "f" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-t",
    tool: "vim",
    mode: "normal",
    actionId: "cursor.till.char.forward",
    action: "Till character forward",
    sequence: [{ modifiers: [], key: "t" }],
    category: "motion",
    difficulty: 3,
  },
  {
    id: "vim-motion-star",
    tool: "vim",
    mode: "normal",
    actionId: "search.word.under.cursor",
    action: "Search word under cursor",
    sequence: [{ modifiers: ["shift"], key: "8" }],
    category: "search",
    difficulty: 3,
  },
  {
    id: "vim-edit-dot",
    tool: "vim",
    mode: "normal",
    actionId: "edit.repeat",
    action: "Repeat last change",
    sequence: [{ modifiers: [], key: "." }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-motion-ctrl-d",
    tool: "vim",
    mode: "normal",
    actionId: "scroll.down.halfPage",
    action: "Scroll down half page",
    sequence: [{ modifiers: ["ctrl"], key: "d" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-motion-ctrl-u",
    tool: "vim",
    mode: "normal",
    actionId: "scroll.up.halfPage",
    action: "Scroll up half page",
    sequence: [{ modifiers: ["ctrl"], key: "u" }],
    category: "motion",
    difficulty: 2,
  },
  {
    id: "vim-window-ctrl-w-v",
    tool: "vim",
    mode: "normal",
    actionId: "window.split.vertical",
    action: "Split window vertically",
    sequence: [{ modifiers: ["ctrl"], key: "w" }, { modifiers: [], key: "v" }],
    category: "window",
    difficulty: 3,
  },
  {
    id: "vim-window-ctrl-w-s",
    tool: "vim",
    mode: "normal",
    actionId: "window.split.horizontal",
    action: "Split window horizontally",
    sequence: [{ modifiers: ["ctrl"], key: "w" }, { modifiers: [], key: "s" }],
    category: "window",
    difficulty: 3,
  },
  {
    id: "vim-window-ctrl-w-h",
    tool: "vim",
    mode: "normal",
    actionId: "window.focus.left",
    action: "Move to left window",
    sequence: [{ modifiers: ["ctrl"], key: "w" }, { modifiers: [], key: "h" }],
    category: "window",
    difficulty: 3,
  },
  {
    id: "vim-window-ctrl-w-l",
    tool: "vim",
    mode: "normal",
    actionId: "window.focus.right",
    action: "Move to right window",
    sequence: [{ modifiers: ["ctrl"], key: "w" }, { modifiers: [], key: "l" }],
    category: "window",
    difficulty: 3,
  },
  {
    id: "vim-mark-m",
    tool: "vim",
    mode: "normal",
    actionId: "mark.set",
    action: "Set mark",
    sequence: [{ modifiers: [], key: "m" }],
    category: "mark",
    difficulty: 4,
  },
  {
    id: "vim-mark-backtick",
    tool: "vim",
    mode: "normal",
    actionId: "mark.jump",
    action: "Jump to mark",
    sequence: [{ modifiers: [], key: "`" }],
    category: "mark",
    difficulty: 4,
  },
  {
    id: "vim-edit-r",
    tool: "vim",
    mode: "normal",
    actionId: "edit.replace.char",
    action: "Replace character",
    sequence: [{ modifiers: [], key: "r" }],
    category: "edit",
    difficulty: 2,
  },
  {
    id: "vim-edit-J",
    tool: "vim",
    mode: "normal",
    actionId: "edit.join.lines",
    action: "Join lines",
    sequence: [{ modifiers: ["shift"], key: "j" }],
    category: "edit",
    difficulty: 3,
  },
  {
    id: "vim-exit-escape",
    tool: "vim",
    mode: "insert",
    actionId: "mode.normal",
    action: "Exit insert mode",
    sequence: [{ modifiers: [], key: "escape" }],
    category: "mode",
    difficulty: 1,
  },
];

export const vim: ToolDefinition = {
  id: "vim",
  name: "Vim",
  modes: [
    { id: "normal", name: "Normal", defaultMode: true },
    { id: "insert", name: "Insert" },
    { id: "visual", name: "Visual" },
    { id: "command", name: "Command" },
  ],
  bindings,
  difficultyCurve: {
    warmup: 10,
    mastery: 100,
  },
};